[package]
authors = ["Oliver Schneider <priroda-tsm-i-77ksi-11f77i@oli-obk.de>"]
description = "A graphical debugger for Rust MIR."
license = "MIT/Apache-2.0"
name = "priroda"
repository = "https://github.com/oli-obk/priroda"
version = "0.1.0"
edition = "2018"


[dependencies]
regex = "1.0"
lazy_static = "1.0.0"
rocket = { git = "https://github.com/oli-obk/Rocket.git" }
rocket_codegen = { git = "https://github.com/oli-obk/Rocket.git" }
miri = { git = "https://github.com/solson/miri.git", branch = "master" }

log = "0.4"
env_logger = "0.6"

serde = "1.0.66"
serde_derive = "1.0.66"
serde_json = "1.0.20"

open = "1.2.2"
promising-future = "0.2"
syntect = "3.0.2"
horrorshow = "0.6.2"
cgraph = { git = "https://github.com/oli-obk/cgraph.git", rev = "b65e460ee323b31dca55b5541141a6b73272e72a" }
rental = "0.5.1"
inferno = "0.3.0"

# Uncomment to use local checkout of miri
# [patch."https://github.com/solson/miri.git"]
# miri = { path = "../miri" }

[target.heroku]
version = "nightly"

[features]
static_resources = []
