[package]
authors = ["Oliver Schneider <priroda-tsm-i-77ksi-11f77i@oli-obk.de>"]
description = "A graphical debugger for Rust MIR."
license = "MIT/Apache-2.0"
name = "priroda"
repository = "https://github.com/oli-obk/priroda"
version = "0.1.0"

[dependencies]
regex = "1.0"
lazy_static = "1.0.0"
rocket = "0.3.8"
rocket_codegen = "0.3.8"
miri = { git = "https://github.com/solson/miri.git" }

log = "0.4"
env_logger = "0.5"

serde = "1.0.66"
serde_derive = "1.0.66"
serde_json = "1.0.20"

open = "1.1.1"
promising-future = "0.2"
syntect = "2.0.0"
horrorshow = "0.6.2"
cgraph = { git = "https://github.com/oli-obk/cgraph.git", rev = "b65e460ee323b31dca55b5541141a6b73272e72a" }

rustdoc = { path = "../rust-fork/src/librustdoc" }

# Uncomment to use local checkout of miri
[patch."https://github.com/solson/miri.git"]
miri = { path = "../miri" }

[target.heroku]
version = "nightly"

[features]
static_resources = []
